[build]
  command = "yarn build"
  publish = "dist"

[[redirects]]
  from = "/site/:id"
  to = "https://dhryhmkhdelwuzowyjbo.supabase.co/functions/v1/view-site/:id"
  status = 200
  force = true

[[redirects]]
  from = "/api/generate"
  to = "https://dhryhmkhdelwuzowyjbo.supabase.co/functions/v1/generate-site"
  status = 200
  force = true

[[redirects]]
  from = "/api/generate/*"
  to = "https://dhryhmkhdelwuzowyjbo.supabase.co/functions/v1/generate-site"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://dhryhmkhdelwuzowyjbo.supabase.co/functions/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
